/**
 * Material You (Material Design 3) color schemes.
 * Colors follow the M3 tonal palette system with primary, secondary, tertiary,
 * surface, background, error and their corresponding on-* foreground colors.
 */

export const lightTheme = {
    dark: false,
    colors: {
        background: '#FEF7FF',
        'on-background': '#1D1B20',
        surface: '#FEF7FF',
        'on-surface': '#1D1B20',
        'surface-variant': '#E7E0EC',
        'on-surface-variant': '#49454F',
        'surface-container': '#F3EDF7',
        'on-surface-container': '#1D1B20',
        'surface-container-high': '#ECE6F0',
        'on-surface-container-high': '#1D1B20',
        'surface-container-highest': '#E6E0E9',
        'on-surface-container-highest': '#1D1B20',
        primary: '#6750A4',
        'on-primary': '#FFFFFF',
        'primary-container': '#EADDFF',
        'on-primary-container': '#21005D',
        secondary: '#625B71',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#E8DEF8',
        'on-secondary-container': '#1D192B',
        tertiary: '#7D5260',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#FFD8E4',
        'on-tertiary-container': '#31111D',
        error: '#B3261E',
        'on-error': '#FFFFFF',
        'error-container': '#F9DEDC',
        'on-error-container': '#410E0B',
        outline: '#79747E',
        'outline-variant': '#CAC4D0',
        'inverse-surface': '#322F35',
        'inverse-on-surface': '#F5EFF7',
        'inverse-primary': '#D0BCFF',
    },
    variables: {
        'border-color': '#CAC4D0',
        'border-opacity': 0.12,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.6,
        'disabled-opacity': 0.38,
    },
}

export const darkTheme = {
    dark: true,
    colors: {
        background: '#141218',
        'on-background': '#E6E0E9',
        surface: '#141218',
        'on-surface': '#E6E0E9',
        'surface-variant': '#49454F',
        'on-surface-variant': '#CAC4D0',
        'surface-container': '#211F26',
        'on-surface-container': '#E6E0E9',
        'surface-container-high': '#2B2930',
        'on-surface-container-high': '#E6E0E9',
        'surface-container-highest': '#36343B',
        'on-surface-container-highest': '#E6E0E9',
        primary: '#D0BCFF',
        'on-primary': '#381E72',
        'primary-container': '#4F378B',
        'on-primary-container': '#EADDFF',
        secondary: '#CCC2DC',
        'on-secondary': '#332D41',
        'secondary-container': '#4A4458',
        'on-secondary-container': '#E8DEF8',
        tertiary: '#EFB8C8',
        'on-tertiary': '#492532',
        'tertiary-container': '#633B48',
        'on-tertiary-container': '#FFD8E4',
        error: '#F2B8B5',
        'on-error': '#601410',
        'error-container': '#8C1D18',
        'on-error-container': '#F9DEDC',
        outline: '#938F99',
        'outline-variant': '#49454F',
        'inverse-surface': '#E6E0E9',
        'inverse-on-surface': '#322F35',
        'inverse-primary': '#6750A4',
    },
    variables: {
        'border-color': '#49454F',
        'border-opacity': 0.12,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.6,
        'disabled-opacity': 0.38,
    },
}
